services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=customer-r2dbc-vs-jdbc"
    volumes:
      - "./data-storage/data:/var/lib/postgresql/data"
      - "./sql/customer.sql:/docker-entrypoint-initdb.d/customer.sql"
