spring:
  application:
    name: traditional-jdbc
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-r2dbc-vs-jdbc
    username: postgres
    password: password